### PR TITLE
Use `notImplemented` to populate tables.

### PR DESCRIPTION
**Pull request by JSAssassin**

### CODE REVIEW

**Review by aljones15 — APPROVED** [review]
Approving assuming this has been tested and working etc.

**Review by aljones15 — APPROVED** [review]
Approving assuming this has been tested and working etc.

**Comment by JSAssassin** [comment]
@aljones15 this is what the report looks like right now https://w3c-ccg.github.io/status-list-2021-test-suite/. Any feedbacks?

**Comment by aljones15** [comment]
@JSAssassin I went ahead and merged this into initial. Report looks fine. Can we get this code into main this week?

**Pull request merged**
